version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
